//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caycanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDatHang
    {
        public string MaSanPham { get; set; }
        public string MaDonDatHang { get; set; }
        public string MaCay { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
    
        public virtual CayCanh CayCanh { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
